spring:
  application:
    name: nhl-stats-api
  datasource:
    url: jdbc:postgresql://localhost:5432/nhl_stats
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        batch_size: 50
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

